export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const MESSAGE_PUSHED = 'MESSAGE_PUSHED';
export const MESSAGES_PUSHED_TO_STORE = 'MESSAGES_PUSHED_TO_STORE';
export const SEND_CHART_DATA = 'SEND_CHART_DATA';
